Feat/factory page
macleysousa/forest_web_2.0 pull request #16
Opened 2024-02-09 16:51 UTC by inocencio5117

- Adicionado página de Fábrica
- Correções na página de Mobile/distributor-stock
- Correções no scroll do componente Sidebar
- Correções no logout do usuário

2024-02-09 19:19 UTC, inolopesm requested changes

2024-02-09 19:19 UTC, inolopesm commented on src/app/(private)/factory/orders/page.tsx
> +  const cardsContent = [
Podes melhorar aqui colocando essa constante fora da função (acima), assim o js não vai ficar recriando toda vez que re-renderizar

2024-02-09 19:19 UTC, inolopesm commented on src/app/(private)/factory/orders/page.tsx
> +  const [dashboardStatus, setDashboardStatus] = useState<boolean>(true);
Como tem valor inicial, é redudante o `<boolean>`

2024-02-09 19:19 UTC, inolopesm commented on src/app/(private)/factory/pps-stock/page.tsx
> +  const labels = useMemo(
- Seria mesmo necessário o uso do `useMemo` aqui?
- Se remover o `useMemo`, esse array poderia estar fora da função para o js não ficar recriando em toda re-renderização

2024-02-09 19:19 UTC, inolopesm commented on src/app/(private)/factory/pps-stock/page.tsx
> +  const formatData = useCallback(
- Seria mesmo necessário o uso do `useCallback` aqui?
- Até mesmo mover essa função pra acima do componente
- Ou melhor ainda, criar um objeto/array estático contendo todos os valores mockados necessários já bonitinhos

2024-02-09 19:19 UTC, inolopesm commented on src/app/(private)/factory/pps-stock/page.tsx
> +  const id = useRef<string>(generateRandomId());
Não entendi

2024-02-11 20:17 UTC, macleysousa approved these changes

2024-02-11 20:17 UTC, merged